// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Balances.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientBalanceResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientBalanceResponseModel class.
        /// </summary>
        public ClientBalanceResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientBalanceResponseModel class.
        /// </summary>
        public ClientBalanceResponseModel(double balance, string assetId = default(string), string errorMessage = default(string))
        {
            AssetId = assetId;
            Balance = balance;
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Balance")]
        public double Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
