// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Balances.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IWalletCredentials
    {
        /// <summary>
        /// Initializes a new instance of the IWalletCredentials class.
        /// </summary>
        public IWalletCredentials()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IWalletCredentials class.
        /// </summary>
        public IWalletCredentials(bool preventTxDetection, string clientId = default(string), string address = default(string), string publicKey = default(string), string privateKey = default(string), string multiSig = default(string), string coloredMultiSig = default(string), string encodedPrivateKey = default(string), string btcConvertionWalletPrivateKey = default(string), string btcConvertionWalletAddress = default(string), string ethConversionWalletAddress = default(string), string ethAddress = default(string), string ethPublicKey = default(string), string solarCoinWalletAddress = default(string), string chronoBankContract = default(string), string quantaContract = default(string))
        {
            ClientId = clientId;
            Address = address;
            PublicKey = publicKey;
            PrivateKey = privateKey;
            MultiSig = multiSig;
            ColoredMultiSig = coloredMultiSig;
            PreventTxDetection = preventTxDetection;
            EncodedPrivateKey = encodedPrivateKey;
            BtcConvertionWalletPrivateKey = btcConvertionWalletPrivateKey;
            BtcConvertionWalletAddress = btcConvertionWalletAddress;
            EthConversionWalletAddress = ethConversionWalletAddress;
            EthAddress = ethAddress;
            EthPublicKey = ethPublicKey;
            SolarCoinWalletAddress = solarCoinWalletAddress;
            ChronoBankContract = chronoBankContract;
            QuantaContract = quantaContract;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PublicKey")]
        public string PublicKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrivateKey")]
        public string PrivateKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MultiSig")]
        public string MultiSig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ColoredMultiSig")]
        public string ColoredMultiSig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PreventTxDetection")]
        public bool PreventTxDetection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EncodedPrivateKey")]
        public string EncodedPrivateKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BtcConvertionWalletPrivateKey")]
        public string BtcConvertionWalletPrivateKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BtcConvertionWalletAddress")]
        public string BtcConvertionWalletAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EthConversionWalletAddress")]
        public string EthConversionWalletAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EthAddress")]
        public string EthAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EthPublicKey")]
        public string EthPublicKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SolarCoinWalletAddress")]
        public string SolarCoinWalletAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChronoBankContract")]
        public string ChronoBankContract { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuantaContract")]
        public string QuantaContract { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
