// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Balances.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TotalBalancesResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the TotalBalancesResponseModel class.
        /// </summary>
        public TotalBalancesResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TotalBalancesResponseModel class.
        /// </summary>
        public TotalBalancesResponseModel(IList<TotalAssetBalance> balances = default(IList<TotalAssetBalance>))
        {
            Balances = balances;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Balances")]
        public IList<TotalAssetBalance> Balances { get; set; }

    }
}
