// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Wallets.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Wallets;
    using Lykke.Service.Wallets.Client;
    using Lykke.Service.Wallets.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientBalanceResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientBalanceResponseModel class.
        /// </summary>
        public ClientBalanceResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientBalanceResponseModel class.
        /// </summary>
        public ClientBalanceResponseModel(string assetId = default(string), double? balance = default(double?), string errorMessage = default(string))
        {
            AssetId = assetId;
            Balance = balance;
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Balance")]
        public double? Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

    }
}
